<a href="https://colab.research.google.com/github/astha-29/Neural-Network/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
pip install tensorflow-gpu

     |████████████████████████████████| 320.4MB 40kB/s 


In [32]:
import tensorflow as tf

In [4]:
tf.__version__

'2.3.0'

In [5]:
a = 1
type(a)

int

In [6]:
tf.ones(2)
# Vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [7]:
tf.ones((4,5))
# Matrix

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [8]:
A=tf.constant([[7,8],
               [5,4]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [5, 4]], dtype=int32)>

In [9]:
V=tf.Variable([[3,1],
               [5,2]])
B=tf.constant([[7,8],
               [5,4]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [5, 4]], dtype=int32)>

In [10]:
#concatinate different values
AB_concatenated = tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[7, 8, 7, 8],
       [5, 4, 5, 4]], dtype=int32)>

In [11]:
tensor =tf.ones(shape=[3,4], dtype= tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [12]:
#typecasting
A =tf.constant([[3,4],
                     [5,6]])
v=tf.constant([[4],
               [2]])
Av=tf.matmul(A,v)
Av

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[20],
       [32]], dtype=int32)>